
# please put your GITHUB_TOKEN below
# docker build --build-arg GITHUB_TOKEN=ghp_XXXXXXXXXXXXXXXXXXXXXX -t ...................

FROM rocm/vllm-dev:nightly_main_20250804
ARG GITHUB_TOKEN=""



RUN bash <<'EOF'

#!/bin/bash
set -ex

apt update --allow-insecure-repositories

apt -y install gcc make libtool autoconf  librdmacm-dev rdmacm-utils infiniband-diags ibverbs-utils perftest ethtool  libibverbs-dev rdma-core strace --allow-unauthenticated
apt -y install openssh-server openmpi-bin openmpi-common libopenmpi-dev --allow-unauthenticated

# COPY from https://amd.atlassian.net/wiki/spaces/NETVAL/pages/528559751/Broadcom+Thor2+RoCE+Support+on+Docker#BroadcomThor2RoCESupportonDocker-2.1StartDocker
echo -e "\n\n============Installing required pkgs============\n\n"
#sudo apt update
#sudo apt -y install linux-headers-"$(uname -r)"  libelf-dev
#sudo apt -y install wget gcc make libtool autoconf  librdmacm-dev rdmacm-utils infiniband-diags ibverbs-utils perftest ethtool  libibverbs-dev rdma-core strace

wget https://docs.broadcom.com/docs-and-downloads/ethernet-network-adapters/NXE/BRCM_233.1.135.7/bcm_233.1.135.7.tar.gz
tar xvzf bcm_233.1.135.7.tar.gz
cd bcm_233.1.135.7/drivers_linux/bnxt_rocelib/
echo -e "\n\n============Compiling RoCE Lib now============\n\n"
tar -xf libbnxt_re-233.0.152.2.tar.gz
     cd libbnxt_re-233.0.152.2
     sh autogen.sh
     ./configure
     make
     find /usr/lib64/  /usr/lib -name "libbnxt_re-rdmav*.so"  -exec mv {} {}.inbox \;
     make install all
     sudo sh -c "echo /usr/local/lib >> /etc/ld.so.conf"
     sudo ldconfig
     cp -f bnxt_re.driver /etc/libibverbs.d/

     find . -name "*.so" -exec md5sum {} \;
     BUILT_MD5SUM=$(find . -name "libbnxt_re-rdmav*.so" -exec md5sum {} \; |  cut -d " " -f 1)
     echo -e "\n\nmd5sum of the built libbnxt_re is $BUILT_MD5SUM"
cd ../../../../
echo $PWD
rm -rf bcm_233.1.135.7.tar.gz  bcm_233.1.135.7

EOF


WORKDIR /app
# RUN rm -rf mori
RUN git clone https://${GITHUB_TOKEN}@github.com/ROCm/mori.git
WORKDIR /app/mori/

RUN git checkout feature_comm_internode
RUN pip install -e .



